ingress_switch_details :
  switch_name: procurve2
  switch_management_ip : "192.168.184.36"
  interface_id : 2
egress_switch_details  :
  switch_name : procurve2
  switch_management_ip : "192.168.184.36"
  interface_id : 5
